# Generated by Django 2.2.6 on 2019-10-14 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_auto_20191011_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('member_name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Book')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Member')),
            ],
        ),
    ]
