# Generated by Django 2.2.6 on 2019-10-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_book_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='book_name',
            new_name='book',
        ),
    ]
