# Generated by Django 2.2.6 on 2019-10-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_auto_20191014_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
